- id: '1640833273099'
  alias: NWS Announce Weather Alert for Tornado
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.weatheralerts_active_alerts
    attribute: tornado_warning_count
    above: '0'
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.audible_notifications
  - service: script.max_brightness
    data: {}
  - service: notify.all_ios
    data:
      title: Tornado Warning - TAKE COVER!
      message: The National Weather Service has issued a Tornado Warning for our area.
        Take Cover NOW!!!!
  - service: notify.tv_notifications
    data:
      title: Tornado Warning - TAKE COVER!
      message: The National Weather Service has issued a Tornado Warning for our area.
        Take Cover NOW!!!!
  - service: script.speech_engine
    data:
      who: everywhere
      message: A tornado warning has been issued, please take cover immediately! A
        tornado warning has been issued, please take cover immediately! A tornado
        warning has been issued, please take cover immediately!
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: script.speech_engine
    data:
      who: everywhere
      message: A tornado warning has been issued, please take cover immediately! A
        tornado warning has been issued, please take cover immediately! A tornado
        warning has been issued, please take cover immediately!
  mode: single
- id: '1640916845901'
  alias: Cast to Chromecast
  description: ''
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace
      player: media_player.living_room_tv
      view: chromecast
- id: '1640989510134'
  alias: New Years
  description: Flash lights for New Years
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - basement_studio
      - furnace_room
      - kallen_bedroom
      - living_room
      - master_bedroom
      - mud_room
      - nursery
      - upstairs_hallway
  - service: switch.turn_off
    target:
      entity_id:
      - switch.adaptive_lighting_basement_studio
      - switch.adaptive_lighting_kallen_bedroom
      - switch.adaptive_lighting_living_room
      - switch.adaptive_lighting_master_bedroom
      - switch.adaptive_lighting_mud_room
      - switch.adaptive_lighting_nursery
      - switch.adaptive_lighting_upstairs_hallway
  - service: notify.alexa_media
    data:
      target: Living Room Echo Dot
      message: Happy new year! Here's to 2022!
      data:
        method: all
        type: announce
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    target:
      entity_id:
      - light.hallway_overhead
      - light.kallen_bedroom_lights
      - light.living_room_color_1
      - light.living_room_color_2
      - light.master_bedroom_front
      - light.master_bedroom_side
      - light.mud_room_overhead
      - light.nursery_light
    data:
      flash: long
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: light.turn_off
    target:
      area_id:
      - basement_studio
      - furnace_room
      - kallen_bedroom
      - living_room
      - master_bedroom
      - mud_room
      - nursery
      - upstairs_hallway
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: switch.turn_on
    target:
      entity_id:
      - switch.adaptive_lighting_basement_studio
      - switch.adaptive_lighting_kallen_bedroom
      - switch.adaptive_lighting_living_room
      - switch.adaptive_lighting_master_bedroom
      - switch.adaptive_lighting_mud_room
      - switch.adaptive_lighting_nursery
      - switch.adaptive_lighting_upstairs_hallway
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: light.turn_on
    target:
      area_id:
      - living_room
      - mud_room
  mode: single
- id: '1641101491581'
  alias: Family Has Arrived
  description: Runs when family arrives at home
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: We Are Home
  condition: []
  action:
  - service: script.family_is_home
  mode: single
- id: '1641102018783'
  alias: Family Has Left
  description: Runs when the family has left home
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: We Are Leaving
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: script.family_is_away
  mode: single
- id: '1641255231416'
  alias: Goodnight
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Goodnight
    context: {}
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.goodnight
  mode: single
- id: '1641255482975'
  alias: Give Me Darkness
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Give Me Darkness
  condition: []
  action:
  - service: script.give_me_darkness
  mode: single
- id: '1643321652916'
  alias: Time-Based Presence Simulation
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.presence_simulation
  mode: single
- id: '1644510872801'
  alias: iCloud3 Restart
  description: For restarting iCloud3 when my phone goes off the rails
  trigger:
  - platform: state
    entity_id: sensor.tony_s_iphone_info
    to: ●● PAUSED ●●
  condition: []
  action:
  - service: device_tracker.icloud3_restart
    data: {}
  mode: single
- id: '1645738561470'
  alias: Cast to Basement TV
  description: ''
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace
      player: media_player.basement_tv_chromecast
      view: chromecast
- id: '1651785688186'
  alias: Watchman Audit on Startup
  description: Runs the Watchman Audit script after Home Assistant has successfully
    started up
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: script.watchman_audit
    data: {}
  mode: single
- id: '1651787468337'
  alias: Reboot handling
  description: ''
  trigger:
  - platform: homeassistant
    event: start
    id: hass_start
  - platform: homeassistant
    event: shutdown
    id: hass_stop
  condition: []
  action:
  - if:
    - condition: trigger
      id: hass_start
    then:
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - service: automation.turn_on
      data: {}
      target:
        entity_id:
        - automation.family_has_arrived
        - automation.family_has_left
    - service: switch.turn_off
      target:
        entity_id:
        - switch.presence_simulation
      data: {}
    - service: script.status_annc
      data_template:
        who: basement
        call_ha_started: 1
  - if:
    - condition: trigger
      id: hass_stop
    then:
    - service: automation.turn_off
      data: {}
      target:
        entity_id:
        - automation.family_has_arrived
        - automation.family_has_left
  mode: queued
- id: '1654547257475'
  alias: Battery Monitoring
  description: Monitor all battery-powered things for low battery states
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '11:00:00'
      exclude:
        entity_id:
        - sensor.iphone_battery_level
        - sensor.kallen_iphone_battery_level
        - sensor.tinas_ipad_battery_level
        - sensor.tony_s_iphone_battery_level
        - sensor.tony_s_ipad_battery_level
      actions:
      - service: script.text_notify_all
        data:
          title: Low Batteries in House
          message: 'Low battery alert for: {{sensors}}'
- id: '1655415573165'
  alias: Nursery Cooling
  description: For keeping the baby’s room at a safe temperature
  trigger:
  - platform: time
    at: input_datetime.nursery_cooling
  condition:
  - condition: numeric_state
    entity_id: sensor.tonights_low_temp
    above: '50'
  action:
  - service: fan.turn_on
    data: {}
    target:
      entity_id: fan.nursery_air_conditioner
  mode: queued
- id: '1655493590791'
  alias: NWS Announce Weather Alert for Tornado (CLEAR)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.weatheralerts_active_alerts
    attribute: tornado_warning_count
    below: '1'
  condition: []
  action:
  - service: script.max_brightness_cleanup
    data: {}
  - service: notify.all_ios
    data:
      title: Check your surroundings and make sure it is safe to leave cover
      message: Tornado Warning is cleared
  - service: notify.tv_notifications
    data:
      title: Check your surroundings and make sure it is safe to leave cover
      message: Tornado Warning is cleared
  - service: script.speech_engine
    data:
      who: everywhere
      message: Tornado warning has been cleared. Check your surroundings and make
        sure it is safe to leave cover.
  mode: single
