- id: '1640833273099'
  alias: NWS Announce Weather Alert for Tornado
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.weatheralerts_active_alerts
    attribute: tornado_warning_count
    above: '0'
  condition: []
  action:
  - service: script.max_brightness
    data: {}
  - service: notify.all_ios
    data:
      title: Tornado Warning - TAKE COVER!
      message: The National Weather Service has issued a Tornado Warning for our area.
        Take Cover NOW!!!!
  - service: notify.tv_notifications
    data:
      title: Tornado Warning - TAKE COVER!
      message: The National Weather Service has issued a Tornado Warning for our area.
        Take Cover NOW!!!!
  - service: notify.alexa_media
    data:
      data:
        method: all
        type: announce
      message: A tornado warning has been issued, please take cover immediately! A
        tornado warning has been issued, please take cover immediately! A tornado
        warning has been issued, please take cover immediately!
      target: Living Room Echo Dot, Basement Echo Dot, Master Bedroom Echo Dot
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: notify.alexa_media
    data:
      data:
        method: all
        type: announce
      message: A tornado warning has been issued, please take cover immediately! A
        tornado warning has been issued, please take cover immediately! A tornado
        warning has been issued, please take cover immediately!
      target: Living Room Echo Dot, Basement Echo Dot, Master Bedroom Echo Dot
  mode: single
- id: '1640916845901'
  alias: Cast to Chromecast
  description: ''
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace
      player: media_player.living_room_tv
      view: chromecast
- id: '1640989510134'
  alias: New Years
  description: Flash lights for New Years
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - basement_studio
      - furnace_room
      - kallen_bedroom
      - living_room
      - master_bedroom
      - mud_room
      - nursery
      - upstairs_hallway
  - service: switch.turn_off
    target:
      entity_id:
      - switch.adaptive_lighting_basement_studio
      - switch.adaptive_lighting_kallen_bedroom
      - switch.adaptive_lighting_living_room
      - switch.adaptive_lighting_master_bedroom
      - switch.adaptive_lighting_mud_room
      - switch.adaptive_lighting_nursery
      - switch.adaptive_lighting_upstairs_hallway
  - service: notify.alexa_media
    data:
      target: Living Room Echo Dot
      message: Happy new year! Here's to 2022!
      data:
        method: all
        type: announce
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    target:
      entity_id:
      - light.hallway_overhead
      - light.kallen_bedroom_light
      - light.living_room_color_1
      - light.living_room_color_2
      - light.master_bedroom_front
      - light.master_bedroom_side
      - light.mud_room_overhead
      - light.nursery_light
    data:
      flash: long
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: light.turn_off
    target:
      area_id:
      - basement_studio
      - furnace_room
      - kallen_bedroom
      - living_room
      - master_bedroom
      - mud_room
      - nursery
      - upstairs_hallway
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: switch.turn_on
    target:
      entity_id:
      - switch.adaptive_lighting_basement_studio
      - switch.adaptive_lighting_kallen_bedroom
      - switch.adaptive_lighting_living_room
      - switch.adaptive_lighting_master_bedroom
      - switch.adaptive_lighting_mud_room
      - switch.adaptive_lighting_nursery
      - switch.adaptive_lighting_upstairs_hallway
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: light.turn_on
    target:
      area_id:
      - living_room
      - mud_room
  mode: single
- id: '1641101491581'
  alias: Family Has Arrived
  description: Runs when family arrives at home
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: We Are Home
  condition: []
  action:
  - service: script.family_is_home
  mode: single
- id: '1641102018783'
  alias: Family Has Left
  description: Runs when the family has left home
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: We Are Leaving
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: script.family_is_away
  mode: single
- id: '1641255231416'
  alias: Goodnight
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Goodnight
    context: {}
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.goodnight
  mode: single
- id: '1641255482975'
  alias: Give Me Darkness
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Give Me Darkness
  condition: []
  action:
  - service: script.give_me_darkness
  mode: single
- id: '1643321652916'
  alias: Time-Based Presence Simulation
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.presence_simulation
  mode: single
- id: '1644510872801'
  alias: iCloud3 Restart
  description: For restarting iCloud3 when my phone goes off the rails
  trigger:
  - platform: state
    entity_id: sensor.tony_s_iphone_info
    to: ●● PAUSED ●●
  condition: []
  action:
  - service: device_tracker.icloud3_restart
    data: {}
  mode: single
- id: '1644528841392'
  alias: Dining Room Lamp Modes
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.dining_room_lamp_modes
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.dining_room_lamp_modes
        state: All Bulbs
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_dining_room
      - service: scene.turn_on
        data: {}
        target:
          entity_id: scene.dining_room_lamp_full
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
      - service: adaptive_lighting.apply
        data:
          entity_id: switch.adaptive_lighting_dining_room
    - conditions:
      - condition: state
        entity_id: input_select.dining_room_lamp_modes
        state: 3 Bulb - Dining Room
      sequence:
      - service: scene.turn_on
        data: {}
        target:
          entity_id: scene.dining_room_lamp_dining_side
    - conditions:
      - condition: state
        entity_id: input_select.dining_room_lamp_modes
        state: 2 Bulb - Wall
      sequence:
      - service: scene.turn_on
        data: {}
        target:
          entity_id: scene.dining_room_lamp_wall
    - conditions:
      - condition: state
        entity_id: input_select.dining_room_lamp_modes
        state: Nightlight
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_dining_room
    - conditions:
      - condition: state
        entity_id: input_select.dining_room_lamp_modes
        state: Reset
      sequence:
      - service: input_select.select_option
        data:
          option: All Bulbs
        target:
          entity_id: input_select.dining_room_lamp_modes
    default: []
  mode: queued
  max: 2
- id: '1645738561470'
  alias: Cast to Basement TV
  description: ''
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace
      player: media_player.basement_tv_chromecast
      view: chromecast
- id: '1650223622885'
  alias: Kallen Bedtime Protocol
  description: Activates fan or white noise at bedtime depending on temperature (turning
    down speaker volume as well) and then shuts them off in the morning.
  trigger:
  - platform: time
    id: kallen-night
    at: input_datetime.kallen_bedtime
  - platform: time
    id: kallen-morning
    at: input_datetime.kallen_wakeup_time
  condition:
  - condition: state
    entity_id: binary_sensor.people_present
    state: 'on'
  - condition: state
    entity_id: input_boolean.kallen_overnight
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: kallen-night
      sequence:
      - choose:
        - conditions:
          - condition: numeric_state
            entity_id: sensor.pirateweather_temperature
            below: '40'
          sequence:
          - service: light.turn_on
            data: {}
            target:
              area_id:
              - kallen_bedroom
              - upstairs_bathroom
              - upstairs_hallway
          - service: script.speech_engine
            data:
              who: kallen_bedroom
              message: No fan tonight, too cold outside! Brrrr!
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: media_player.volume_set
            data:
              volume_level: 0.3
            target:
              entity_id: media_player.kallen_bedroom_speaker
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.white_noise_kallen_bedroom
        default:
        - service: light.turn_on
          data: {}
          target:
            area_id:
            - kallen_bedroom
            - upstairs_bathroom
            - upstairs_hallway
        - service: script.speech_engine
          data:
            who: kallen_bedroom
            message: Fan on. Stay cool!
        - service: media_player.volume_set
          data:
            volume_level: 0.3
          target:
            entity_id: media_player.kallen_bedroom_speaker
        - service: fan.turn_on
          data: {}
          target:
            entity_id: fan.kallen_fan_socket_1
    - conditions:
      - condition: trigger
        id: kallen-morning
      sequence:
      - service: fan.turn_off
        data: {}
        target:
          entity_id: fan.kallen_fan_socket_1
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.white_noise_kallen_bedroom
    default: []
  mode: queued
- id: '1650918265367'
  alias: Speedtest Schedule
  description: Runs an internet speed test on a schedule UNLESS Tony or Tina are streaming
    on Twitch.
  trigger:
  - platform: time_pattern
    hours: /4
  condition:
  - condition: state
    entity_id: sensor.twitch_ironnerd24
    state: offline
  - condition: state
    entity_id: sensor.twitch_xia_p988
    state: offline
  action:
  - service: speedtestdotnet.speedtest
    data: {}
  mode: single
- id: '1651785688186'
  alias: Watchman Audit on Startup
  description: Runs the Watchman Audit script after Home Assistant has successfully
    started up
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: script.watchman_audit
    data: {}
  mode: single
- id: '1651787468337'
  alias: Reboot handling
  description: ''
  trigger:
  - platform: homeassistant
    event: start
    id: hass_start
  - platform: homeassistant
    event: shutdown
    id: hass_stop
  condition: []
  action:
  - if:
    - condition: trigger
      id: hass_start
    then:
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - service: automation.turn_on
      data: {}
      target:
        entity_id:
        - automation.family_has_arrived
        - automation.family_has_left
    - service: switch.turn_off
      target:
        entity_id:
        - switch.presence_simulation
  - if:
    - condition: trigger
      id: hass_stop
    then:
    - service: automation.turn_off
      data: {}
      target:
        entity_id:
        - automation.family_has_arrived
        - automation.family_has_left
  mode: queued
- id: '1652215901673'
  alias: Master Bedroom Nighttime Protocol
  description: Management of the fan and air conditioner in the master bedroom
  trigger:
  - platform: time
    at: input_datetime.master_bedroom_cooling
    id: master-bedroom-cooling
  - platform: time
    at: input_datetime.master_bedroom_wakeup
    id: master-bedroom-wakeup
  - platform: time
    at: input_datetime.master_bedroom_fan
    id: master-bedroom-fan
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: master-bedroom-cooling
      sequence:
      - if:
        - condition: numeric_state
          entity_id: sensor.current_forecast
          attribute: overnight_low
          above: '50'
        then:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.master_bedroom_aircon
        - parallel:
          - service: script.text_notify_tony
            data:
              title: AC Schedule Activated
              message: '"Master bedroom AC has been activated, as scheduled based
                on tonight''s forecast low"'
          - service: script.text_notify_tina
            data:
              title: AC Schedule Activated
              message: '"Master bedroom AC has been activated, as scheduled based
                on tonight''s forecast low"'
        else:
        - parallel:
          - service: script.text_notify_tony
            data:
              title: AC Schedule Skipped
              message: Too cold outside, AC not activated
          - service: script.text_notify_tina
            data:
              title: AC Schedule Skipped
              message: Too cold outside, AC not activated
    - conditions:
      - condition: trigger
        id: master-bedroom-fan
      sequence:
      - if:
        - condition: numeric_state
          entity_id: sensor.current_forecast
          attribute: overnight_low
          above: '40'
        then:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.master_bedroom_fan_socket_1
        - parallel:
          - service: script.text_notify_tony
            data:
              title: Fan Schedule Activated
              message: '"Master bedroom fan has been activated, as scheduled based
                on tonight''s forecast low"'
          - service: script.text_notify_tina
            data:
              title: Fan Schedule Activated
              message: '"Master bedroom fan has been activated, as scheduled based
                on tonight''s forecast low"'
    - conditions:
      - condition: trigger
        id: master-bedroom-wakeup
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
          - switch.master_bedroom_fan_socket_1
          - switch.master_bedroom_aircon
          - switch.master_bedroom_echo_dot_do_not_disturb_switch
    default:
    - service: script.text_notify_tony
      data:
        title: Master Bedroom Info
        message: '"Today''s wakeup time is set to {{ states(''input_datetime.master_bedroom_wakeup'')
          }} and tonight''s cooling is set to start at {{ states(''input_datetime.master_bedroom_cooling'')
          }}"'
  mode: queued
- id: '1654547257475'
  alias: Battery Monitoring
  description: Monitor all battery-powered things for low battery states
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '11:00:00'
      exclude:
        entity_id:
        - sensor.iphone_battery_level
        - sensor.kallen_iphone_battery_level
        - sensor.tinas_ipad_battery_level
        - sensor.tony_s_iphone_battery_level
        - sensor.tony_s_ipad_battery_level
        - sensor.kallen_desktop_battery_level
        - sensor.kallen_desktop_battery_remaining
        - sensor.tony_asus_battery_level
        - sensor.tony_asus_battery_remaining
        - sensor.xia_desktop_battery_level
        - sensor.xia_desktop_battery_remaining
      actions:
      - service: script.text_notify_all
        data:
          title: Low Batteries in House
          message: 'Low battery alert for: {{sensors}}'
