- platform: workday
  country: US
  province: OH
  workdays: [mon, tue, wed, thu, fri]
- platform: tod
  name: Night
  after: sunset
  before: sunrise
- platform: tod
  name: School
  after: "09:00"
  before: "15:30"
