homeassistant:
    packages: !include_dir_named packages
    customize: !include customize.yaml
    external_url: !secret remote_url
    internal_url: http://homeassistant.local:8123
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Includes

group: !include groups.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations
script: !include scripts.yaml
scene:
  - !include scenes.yaml
  - platform: lifx_cloud
    token: !secret lifx_token
camera: !include cameras.yaml
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include_dir_merge_list sensors
switch: !include switches.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
template: !include template.yaml
localtuya: !include localtuya.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
  - /hacsfiles/hass-hue-icons/hass-hue-icons.js
  - /hacsfiles/hass-bha-icons/hass-bha-icons.js
  javascript_version: latest

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

calendar:
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com
    custom_calendars:
      - name: "TinaWork"
        calendar: "Family"
        search: "Work"
  - platform: todoist
    token: !secret todoist_api_token
    custom_projects:
      - name: 'All Projects'
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7

notify:
  - platform: ios
  - name: all_ios
    platform: group
    services:
      - service: mobile_app_tinas_iphone
      - service: mobile_app_tony_s_iphone
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_kallen_iphone
  - name: ios_parents
    platform: group
    services:
      - service: mobile_app_tinas_iphone
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_tony_s_iphone
  - name: ios_tony
    platform: group
    services:
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_tony_s_iphone
  - name: ios_tina
    platform: group
    services:
      - service: mobile_app_tinas_iphone
  - name: ios_kallen
    platform: group
    services:
      - service: mobile_app_kallen_iphone
  - name: ios_nerds
    platform: group
    services:
      - service: mobile_app_kallen_iphone
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_tony_s_iphone
  - name: tv_notifications
    platform: group
    services:
      - service: living_room_tv
      - service: basement_tv
      - service: master_bedroom_tv

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v8/sync'
    payload: !secret todoist_api_payload
    content_type: 'application/x-www-form-urlencoded'
