devices:
  - device_name: Tony's iPhone
    name: Tony's iPhone
  - device_name: iPhone
    name: Tina's iPhone
    iosapp_entity: tinas_iphone_app
  - device_name: Kallen's iPhone
    name: Kallen's iPhone
  - device_name: tony_s_apple_watch
    name: Tony's Watch
    iosapp_installed: false
  - device_name: tony_s_ipad
    name: Tony's iPad
  - device_name: christinas_apple_watch
    name: Tina's Watch
    iosapp_installed: false

waze_realtime: true
