homeassistant:
    packages: !include_dir_named packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml

media_player:
  - platform: androidtv
    name: Living Room FireTV
    host: 192.168.1.56
    state_detection_rules:
      'com.amazon.tv.launcher':
        - 'standby'
      'com.netflix.ninja':
        - 'media_session_state'
      'com.amazon.avod':
        - 'standby'

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
  - /hacsfiles/hass-hue-icons/hass-hue-icons.js
