homeassistant:
    packages: !include_dir_named packages
    external_url: !secret remote_url
    internal_url: !secret local_url
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Includes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene:
  - !include scenes.yaml
  - platform: lifx_cloud
    token: !secret lifx_token
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include_dir_merge_list sensors
switch: !include switches.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
template: !include template.yaml
input_number: !include input_number.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
  - /hacsfiles/hass-hue-icons/hass-hue-icons.js
  - /hacsfiles/hass-bha-icons/hass-bha-icons.js
  javascript_version: latest

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

calendar:
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com
    custom_calendars:
      - name: "TinaWork"
        calendar: "Family"
        search: "Work"

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v9/{{ url }}'
    payload: !secret todoist_api_payload
    content_type: 'application/x-www-form-urlencoded'

downloader:
  download_dir: downloads

climate:
  - platform: midea_ac
    host: 192.168.1.168
    id: !secret master_bedroom_ac_id
    token: !secret master_bedroom_ac_token
    k1: !secret master_bedroom_ac_key

recorder:
  # db_url: !secret mariadb_url
  purge_keep_days: 14
  commit_interval: 30
  exclude:
    domains:
      - media_player
      - scan_store
      - zone
    entities:
      - binary_sensor.internet
      - sensor.avg_ping
      - sensor.max_ping
      - sensor.min_ping
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.time_date
      - sensor.time
      - sensor.time_utc
    entity_globs:
      - sensor.basement_server_*

logger:
  default: critical
  logs:
    homeassistant.core: fatal

# influxdb:
#   host: 192.168.1.26
#   port: 8086
#   database: homeassistant
#   username: homeassistant
#   password: !secret influxdb_pass
#   max_retries: 3
#   default_measurement: state
#   exclude:
#     domains:
#       - automation
#       - script
#       - zone
#     entity_globs:
#       - sensor.*battery*

history:
  exclude:
    domains:
      - automation
      - updater

logbook:
  include:
    domains:
      - alarm_control_panel
      - light
      - fan
      - switch
      - climate
    entity_globs:
      - binary_sensor.*_motion
      - binary_sensor.*_occupancy