homeassistant:
    packages: !include_dir_named packages
    external_url: !secret remote_url
    internal_url: !secret local_url
    country: US
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Includes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene:
  - !include scenes.yaml
  - platform: lifx_cloud
    token: !secret lifx_token
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include_dir_merge_list sensors
switch: !include switches.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
template: !include template.yaml
input_number: !include input_number.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
  - /hacsfiles/hass-hue-icons/hass-hue-icons.js
  - /hacsfiles/hass-bha-icons/hass-bha-icons.js
  javascript_version: latest

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.6

calendar:
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com
    custom_calendars:
      - name: "TinaWork"
        calendar: "Family"
        search: "Work"

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v9/{{ url }}'
    payload: '{{ payload }}'
    headers:
      Authorization: !secret todoist_api_token
    content_type: 'application/x-www-form-urlencoded'

downloader:
  download_dir: downloads

climate:
  - platform: midea_ac
    host: 192.168.1.140
    id: !secret master_bedroom_ac_id
    token: !secret master_bedroom_ac_token
    k1: !secret master_bedroom_ac_key

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 14
  commit_interval: 30
  exclude:
    domains:
      - media_player
      - scan_store
      - zone
      - sun
      - scene
      - zone
    entity_globs:
      - sensor.xr500*
      - sensor.*waze*
      - sensor.*birthday
      - sensor.*anniversary
      - sensor.*uptime*
      - sensor.*power
      - sensor.*energy*
      - sensor.*energy_sensor*
      - sensor.*power_sensor
      - sensor.*voltage
      - sensor.*current
      - sensor.*bps_sent
      - sensor.*bps_received
      - sensor.*bytes_sent
      - sensor.*bytes_received
      - binary_sensor.*server_on
      - binary_sensor.*desktop_on
    entities:
      - sensor.avg_ping
      - sensor.max_ping
      - sensor.min_ping
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.time_date
      - sensor.time
      - sensor.time_utc
      - sensor.hacs
      - sensor.mariadb_database_size
  include:
    entities:
      - media_player.living_room_tv
      - media_player.basement_tv
      - media_player.master_bedroom_firetv
      - media_player.everywhere
      - media_player.basement_echo_dot
      - media_player.living_room_echo_dot
      - media_player.master_bedroom_echo_dot
      - media_player.kallen_bedroom_speaker
      - media_player.emma_bedroom_speaker
      - media_player.spotify_iron_nerd
      - media_player.xia_desktop
      - media_player.tony_asus
      - media_player.kallen_desktop
      - media_player.basement_google_speaker

logger:
  default: error
  logs:
    homeassistant.core: fatal

influxdb:
  api_version: 2
  host: 192.168.1.254
  port: 8086
  max_retries: 3
  ssl: false
  organization: !secret influxdb_org
  token: !secret influxdb_token
  bucket: home_assistant
  default_measurement: state
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  ignore_attributes:
    - icon
  exclude:
    entity_globs:
      - binary_sensor.*tamper*
      - light.*screen*
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.time_date
      - sensor.time
      - sensor.time_utc
      - sensor.xr500_gateway_kib_s_received
      - sensor.xr500_gateway_kib_s_sent
      - light.all_lights
      - fan.all_fans
  include:
    domains:
      - sun
      - light
      - climate
      - fan
      - person
    entity_globs:
      - sensor.*power
      - sensor.*energy
      - sensor.*energy_sensor
      - sensor.*power_sensor
      - sensor.*voltage
      - sensor.*current
      - sensor.*cpu*
      - sensor.*gpu*
      - sensor.*memory*
      - sensor.*ram_free*
      - sensor.*ram_used*
      - sensor.*available_free_space
      - sensor.*ping
      - sensor.*free_space*
      - sensor.*uptime*
      - sensor.*tv_time*
      - sensor.*_count
      - sensor.*pirateweather*
      - sensor.*temperature*
      - sensor.*ipad_storage
      - sensor.*iphone_storage
      - sensor.*_open
      - sensor.xr500*
      - sensor.*gas_price
      - sensor.speedtest*
      - sensor.*fan_time
      - sensor.*compressor_time
      - binary_sensor.*motion*
      - binary_sensor.*door*
      - binary_sensor.*window*
      - device_tracker.*iphone*
      - device_tracker.*ipad*
      - device_tracker.*watch*
      - device_tracker.*airpod*
      - binary_sensor.*desktop_on
      - binary_sensor.*server_on
    entities:
      - media_player.living_room_tv
      - media_player.basement_tv
      - media_player.master_bedroom_firetv
      - sensor.doors_open
      - sensor.windows_open
      - sensor.total_faults
      - sensor.blitzortung_lightning_counter
      - sensor.lines_of_code
      - sensor.mariadb_database_size
      - sensor.thermal_comfort_absolutehumidity
      - sensor.outside_lights
      - sensor.temperature_change_per_hour
      - binary_sensor.tina_home
      - binary_sensor.tony_home
      - binary_sensor.kallen_home
      - sensor.tm24fan8_home_assistant_configs_issues
      - binary_sensor.internet
      - binary_sensor.people_present
      - weather.iron_nerd_weather_station
      - sensor.circle_k
      - sensor.kroger
      - sensor.kecks
      - sensor.the_barn
      - sensor.the_big_fish
      - sensor.speedway
      - sensor.meijer
      - sensor.wash_n_fill
      - sensor.marathon_cleveland_avenue
      - sensor.south_side_shell
      - sensor.east_side_shell
      - sensor.shell_ottawa_avenue

logbook:
  include:
    domains:
      - alarm_control_panel
      - light
      - fan
      - switch
      - climate
    entity_globs:
      - binary_sensor.*_motion
      - binary_sensor.*_occupancy
  exclude:
    domains:
      - media_player
    entity_globs:
      - light.*screen*
      - light.dining_room_lamp_*
    entities:
      - binary_sensor.living_room_motion

prometheus:
  filter:
    exclude_entity_globs:
      - binary_sensor.*tamper*
      - light.*screen*
    exclude_entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.time_date
      - sensor.time
      - sensor.time_utc
      - sensor.xr500_gateway_kib_s_received
      - sensor.xr500_gateway_kib_s_sent
      - light.all_lights
      - fan.all_fans
    include_domains:
      - sun
      - light
      - climate
      - fan
      - person
    include_entity_globs:
      - sensor.*power
      - sensor.*energy
      - sensor.*energy_sensor
      - sensor.*power_sensor
      - sensor.*voltage
      - sensor.*current
      - sensor.*cpu*
      - sensor.*gpu*
      - sensor.*memory*
      - sensor.*ram_free*
      - sensor.*ram_used*
      - sensor.*available_free_space
      - sensor.*ping
      - sensor.*free_space*
      - sensor.*uptime*
      - sensor.*tv_time*
      - sensor.*_count
      - sensor.*pirateweather*
      - sensor.*temperature*
      - sensor.*ipad_storage
      - sensor.*iphone_storage
      - sensor.*_open
      - sensor.xr500*
      - sensor.*gas_price
      - sensor.speedtest*
      - sensor.*fan_time
      - sensor.*compressor_time
      - binary_sensor.*motion*
      - binary_sensor.*door*
      - binary_sensor.*window*
      - device_tracker.*iphone*
      - device_tracker.*ipad*
      - device_tracker.*watch*
      - device_tracker.*airpod*
      - binary_sensor.*desktop_on
      - binary_sensor.*server_on
    include_entities:
      - media_player.living_room_tv
      - media_player.basement_tv
      - media_player.master_bedroom_firetv
      - sensor.doors_open
      - sensor.windows_open
      - sensor.total_faults
      - sensor.blitzortung_lightning_counter
      - sensor.lines_of_code
      - sensor.mariadb_database_size
      - sensor.thermal_comfort_absolutehumidity
      - sensor.outside_lights
      - sensor.temperature_change_per_hour
      - binary_sensor.tina_home
      - binary_sensor.tony_home
      - binary_sensor.kallen_home
      - sensor.tm24fan8_home_assistant_configs_issues
      - binary_sensor.internet
      - binary_sensor.people_present
      - weather.iron_nerd_weather_station
      - sensor.circle_k
      - sensor.kroger
      - sensor.kecks
      - sensor.the_barn
      - sensor.the_big_fish
      - sensor.speedway
      - sensor.meijer
      - sensor.wash_n_fill
      - sensor.marathon_cleveland_avenue
      - sensor.south_side_shell
      - sensor.east_side_shell
      - sensor.shell_ottawa_avenue
