homeassistant:
    packages: !include_dir_named packages
    customize: !include customize.yaml
    external_url: !secret remote_url
    internal_url: http://homeassistant.local:8123
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml
input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
switch: !include switches.yaml
input_select: !include input_select.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_room_overhead_1
      - light.living_room_overhead_2
  - platform: group
    name: Master Bedroom Lights
    entities:
      - light.master_bedroom_front
      - light.master_bedroom_side
  - platform: group
    name: Basement Lights
    entities:
      - light.basement_stairwell
      - light.basement_tall_lamp
      - light.basement_short_lamp
  - platform: group
    name: First Floor Lights
    entities:
      - light.living_room_overhead_1
      - light.living_room_overhead_2
      - light.mud_room_overhead
  - platform: group
    name: Second Floor Lights
    entities:
      - light.master_bedroom_front
      - light.master_bedroom_side
      - light.hallway_overhead
      - light.kallen_bedroom_light
      - light.nursery_light
  - platform: group
    name: Basement Studio Lights
    entities:
      - light.basement_stairwell
      - light.basement_tall_lamp
      - light.basement_short_lamp
  - platform: group
    name: Dining Room Lamp
    entities:
      - light.dining_room_lamp_blue
      - light.dining_room_lamp_green
      - light.dining_room_lamp_purple
      - light.dining_room_lamp_red
      - light.dining_room_lamp_white

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
  - /hacsfiles/hass-hue-icons/hass-hue-icons.js

updater:
  include_used_components: true

python_script:

anniversaries:
  sensors:
    - name: Wedding Anniversary
      date: !secret wedding_anniversary
    - name: Tony's Birthday
      date: !secret tony_bday
    - name: Tina's Birthday
      date: !secret tina_bday
    - name: Kallen's Birthday
      date: !secret kallen_bday
    - name: Emmalynn's Birthday
      date: !secret emmalynn_bday

calendar:
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com

device_tracker:
  - platform: icloud3
    username: !secret userIcloud
    password: !secret passIcloud2

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

breaking_changes:

localtuya: !include localtuya.yaml

wake_on_lan:

notify:
  - platform: ios
  - name: all_ios
    platform: group
    services:
      - service: mobile_app_iphone
      - service: mobile_app_tony_s_iphone
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_kallen_iphone
  - name: ios_parents
    platform: group
    services:
      - service: mobile_app_iphone
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_tony_s_iphone
  - name: ios_tony
    platform: group
    services:
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_tony_s_iphone
  - name: ios_tina
    platform: group
    services:
      - service: mobile_app_iphone
  - name: ios_kallen
    platform: group
    services:
      - service: mobile_app_kallen_iphone
  - name: ios_nerds
    platform: group
    services:
      - service: mobile_app_kallen_iphone
      - service: mobile_app_tony_s_ipad
      - service: mobile_app_tony_s_iphone
