devices:
  - device_name: Tony's iPhone
    name: Tony's iPhone
    iosapp_entity: tony_s_iphone_app
    picture: tony.jpg
  - device_name: Tinas iPhone
    name: Tina's iPhone
    iosapp_entity: tinas_iphone_app
    picture: tina.jpg
  - device_name: Kallen iPhone
    name: Kallen iPhone
    iosapp_entity: kallen_iphone_app
    picture: kallen.jpg
  - device_name: tony_s_apple_watch
    name: Tony's Watch
    iosapp_installed: false
  - device_name: tony_s_ipad
    name: Tony's iPad
  - device_name: christinas_apple_watch
    name: Tina's Watch
    iosapp_installed: false
  - device_name: christinas_airpods
    name: Tina's Airpods
    iosapp_installed: false

waze_realtime: true
