- platform: weatheralerts
  state: OH
  zone: 4
  county: 39
- platform: twitch_helix
  client_id: !secret twitch_client_id
  client_secret: !secret twitch_client_secret
  own_channel: ironnerd24
  thumbnail_dimensions: 320x180
  entity_prefix: Twitch_
  channels:
    - ironnerd24
    - Xia_P988
    - ManaSen
    - STPeach
    - BroteinGaming404
    - NotoriosPenguin
- platform: deluge
  host: !secret deluge_ip
  username: !secret deluge_user
  password: !secret deluge_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
- platform: average
  name: 'Average Temperature'
  duration:
    days: 7
  entities:
    - sensor.kdfi_temperature
- platform: average
  name: 'Average Wind Chill'
  duration:
    days: 7
  entities:
    - sensor.kdfi_wind_chill
- platform: average
  name: 'Average Wind Speed'
  duration:
    days: 7
  entities:
    - sensor.kdfi_wind_speed
- platform: rest
  name: Household Tasks
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2285967928
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30
- platform: rest
  name: Kallen Tasks
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2285969005
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30
