- platform: twitch_helix
  client_id: !secret twitch_client_id
  client_secret: !secret twitch_client_secret
  own_channel: ironnerd24
  thumbnail_dimensions: 320x180
  entity_prefix: Twitch_
  channels:
    - ironnerd24
    - Xia_P988
    - ManaSen
    - STPeach
    - BroteinGaming404
    - NotoriosPenguin
- platform: rest
  name: Household Tasks
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2285967928
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30
- platform: rest
  name: Kallen Tasks
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2285969005
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30
- platform: season
  type: astronomical
  name: Current Season
- platform: uptime
  name: Last Boot
- platform: plex_recently_added
  name: Recently Added Videos
  token: !secret plex_token
  host: 192.168.1.4
  port: 32400
  section_types:
    - video
- platform: plex_recently_added
  name: Recently Added Movies
  token: !secret plex_token
  host: 192.168.1.4
  port: 32400
  section_types:
    - movie