- platform: weatheralerts
  state: OH
  zone: 4
  county: 39
- platform: twitch
  client_id: !secret twitch_client
  token: !secret twitch_token
  channels:
    - ironnerd24
    - Xia_P988
- platform: deluge
  host: !secret deluge_ip
  username: !secret deluge_user
  password: !secret deluge_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
