binary_sensor:
  - name: People Present
    state: >
      {{ is_state('person.tony_stork', 'home')
          or is_state('person.christina_stork', 'home') }}
  - name: School Time
    state: >
      {{ is_state('binary_sensor.school', 'on') 
          and is_state('binary_sensor.workday_sensor', 'on') }}
  - name: Tina Work
    state: >
      {{ is_state('calendar.family_tinawork', 'on') }}