- platform: twitch_helix
  client_id: !secret twitch_client_id
  client_secret: !secret twitch_client_secret
  own_channel: ironnerd24
  thumbnail_dimensions: 320x180
  entity_prefix: Twitch_
  channels:
    - ironnerd24
    - Xia_P988
- platform: plex_recently_added
  name: Recently Added on Plex
  token: !secret plex_token
  host: 192.168.1.4
  port: 32400
- platform: template
  sensors:
    basement_tv_current_app:
      friendly_name: 'Basement TV Current App'
      value_template: >-
        {% if is_state('media_player.basement_tv','off') %}
          Off
        {% else %}
          {{ state_attr('media_player.basement_tv','app_name') }}
        {% endif %}
    living_room_tv_current_app:
      friendly_name: 'Living Room TV Current App'
      value_template: >-
        {% if is_state('media_player.living_room_tv','off') %}
          Off
        {% else %}
          {{ state_attr('media_player.living_room_tv','app_name') }}
        {% endif %}
    master_bedroom_tv_current_app:
      friendly_name: 'Master Bedroom TV Current App'
      value_template: >-
        {% if is_state('media_player.master_bedroom_firetv','off') %}
          Off
        {% else %}
          {{ state_attr('media_player.master_bedroom_firetv','app_name') }}
        {% endif %}