- platform: twitch_helix
  client_id: !secret twitch_client_id
  client_secret: !secret twitch_client_secret
  own_channel: ironnerd24
  thumbnail_dimensions: 320x180
  entity_prefix: Twitch_
  channels:
    - ironnerd24
    - Xia_P988
    - ManaSen
    - STPeach
    - BroteinGaming404
    - NotoriosPenguin
- platform: plex_recently_added
  name: Recently Added on Plex
  token: !secret plex_token
  host: 192.168.1.4
  port: 32400
- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - 76561198006931886
    - 76561199249380296
    - 76561198078898192
    - 76561199079356881