- platform: rest
  name: Kallen Tasks
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2285969005
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - project
    - items
  scan_interval: 30
- platform: rest
  name: Home Tech
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    token: !secret todoist_api_token
    project_id: 2285967948
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - project
    - items
  scan_interval: 30
- platform: template
  sensors:
    home_tech_bug_reports:
      friendly_name: 'Bug Reports'
      value_template: "{{ states('sensor.home_tech') }}"
      attribute_templates:
        project: "{{ state_attr('sensor.home_tech', 'project') }}"
        items: "{{ state_attr('sensor.home_tech', 'items')|selectattr('section_id', 'eq', '94865633')|list|selectattr('parent_id','eq',none)|list }}"
    home_tech_new_ideas:
      friendly_name: 'New Ideas'
      value_template: "{{ states('sensor.home_tech') }}"
      attribute_templates:
        project: "{{ state_attr('sensor.home_tech', 'project') }}"
        items: "{{ state_attr('sensor.home_tech', 'items')|selectattr('section_id', 'eq', '81234669')|list|selectattr('parent_id','eq',none)|list }}"
    home_tech_in_progress:
      friendly_name: 'In Progress'
      value_template: "{{ states('sensor.home_tech') }}"
      attribute_templates:
        project: "{{ state_attr('sensor.home_tech', 'project') }}"
        items: "{{ state_attr('sensor.home_tech', 'items')|selectattr('section_id', 'eq', '81234677')|list|selectattr('parent_id','eq',none)|list }}"
    home_tech_long_term:
      friendly_name: 'Long Term or Maintaining'
      value_template: "{{ states('sensor.home_tech') }}"
      attribute_templates:
        project: "{{ state_attr('sensor.home_tech', 'project') }}"
        items: "{{ state_attr('sensor.home_tech', 'items')|selectattr('section_id', 'eq', '88456343')|list|selectattr('parent_id','eq',none)|list }}"
    home_tech_postponed_indefinitely:
      friendly_name: 'Postponed Indefinitely'
      value_template: "{{ states('sensor.home_tech') }}"
      attribute_templates:
        project: "{{ state_attr('sensor.home_tech', 'project') }}"
        items: "{{ state_attr('sensor.home_tech', 'items')|selectattr('section_id', 'eq', '81234736')|list|selectattr('parent_id','eq',none)|list }}"