- platform: season
  type: astronomical
  name: Current Season
- platform: template
  sensors:
    today_is:
      friendly_name: 'Today is'
      value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
    month_is:
      friendly_name: 'Month is'
      value_template: "{{ ['January','February','March','April','May','June','August','September','October','November','December'][now().month-1] }}" 