- platform: season
  type: astronomical
  name: Current Season
- platform: template
  sensors:
    today_is:
      friendly_name: 'Today is'
      value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
    month_is:
      friendly_name: 'Month is'
      value_template: "{{ ['January','February','March','April','May','June','August','September','October','November','December'][now().month-1] }}" 
    school_tomorrow:
      friendly_name: 'School Tomorrow'
      value_template: >-
        {%- set test=(as_timestamp(now())+ (86400)) | timestamp_custom("%Y-%m-%d",true) %}
        {% if states.calendar.kallen_school_days.attributes.start_time == test + " 09:00:00" %}
          on
        {% elif states.calendar.kallen_school_days.attributes.start_time == test + " 08:00:00" %}
          on
        {% else %}
          off
        {% endif %}
    band_tomorrow:
      friendly_name: 'Band Tomorrow'
      value_template: >-
        {%- set test=(as_timestamp(now())+ (86400)) | timestamp_custom("%Y-%m-%d",true) %}
        {% if states.calendar.kallen_school_days.attributes.start_time == test + " 08:00:00" %}
          on
        {% else %}
          off
        {% endif %}
    work_tomorrow:
      friendly_name: 'Work Tomorrow'
      value_template: >-
        {%- set test=(as_timestamp(now())+ (86400)) | timestamp_custom("%Y-%m-%d",true) %}
        {% if states.calendar.family_tinawork.attributes.start_time == test + " 09:00:00" %}
          on
        {% elif states.calendar.family_tinawork.attributes.start_time == test + " 07:00:00" %}
          on
        {% elif states.calendar.family_tinawork.attributes.start_time == test + " 10:00:00" %}
          on
        {% else %}
          off
        {% endif %}
    kallen_timer_remaining_minutes:
      friendly_name: 'Kallen Timer Remaining Minutes'
      value_template: >-
        {% set f = state_attr('timer.kallen_timer','finishes_at') %}
        {{ '00' if f == none else
          (as_datetime(f) - now()).total_seconds() | timestamp_custom('%M', false) }}
    kallen_timer_remaining_seconds:
      friendly_name: 'Kallen Timer Remaining Seconds'
      value_template: >-
        {% set f = state_attr('timer.kallen_timer','finishes_at') %}
        {{ '00' if f == none else
          (as_datetime(f) - now()).total_seconds() | timestamp_custom('%S', false) }}

- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'time_date'
  - 'time_utc'
  - 'beat'