alert:
  furnace_room_light:
    name: Furnace Room light has been left on
    done_message: Thank you for turning off the furnace room light!
    entity_id: light.furnace_room_overhead
    state: "on"
    repeat:
      - 30
      - 30
      - 60
    can_acknowledge: false
    skip_first: true
    notifiers:
      - tv_notifications
      - ios_tony
      - ios_tina
      - ios_kallen
  front_door_open:
    name: Front Door has been left open
    done_message: Someone finally shut the front door! It's about damn time!
    entity_id: binary_sensor.front_door
    state: "on"
    repeat:
      - 5
    can_acknowledge: false
    skip_first: true
    notifiers:
      - tv_notifications
      - ios_tony
      - ios_tina
      - ios_kallen
  back_door_open:
    name: Back Door has been left open
    done_message: Someone finally shut the back door! It's about damn time!
    entity_id: binary_sensor.back_door
    state: "on"
    repeat:
      - 5
    can_acknowledge: false
    skip_first: true
    notifiers:
      - tv_notifications
      - ios_tony
      - ios_tina
      - ios_kallen

automation:
  - id: 5a82b718-3846-452b-9aa4-a183a88c8f29
    alias: Door Open Alert
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 2
          seconds: 0
    action:
      - service: script.status_annc
        data:
          who: 'living_room'
          call_interuption: 1
          call_snark_door_open: 1