sensor:
  - platform: template
    sensors:
      master_bedroom_current_temp:
        friendly_name: "Master Bedroom Current Temp"
        value_template: >
          {{ state_attr('climate.master_bedroom_aircon','current_temperature') | float }}
      master_bedroom_outdoor_temp:
        friendly_name: "Master Bedroom Outdoor Temp"
        value_template: >
          {{ state_attr('climate.master_bedroom_aircon','outdoor_temperature') | float }}
      master_bedroom_target_temp:
        friendly_name: "Master Bedroom Target Temp"
        value_template: >
          {{ state_attr('climate.master_bedroom_aircon','temperature') | float }}
      master_bedroom_aircon_eco_mode:
        friendly_name: "Master Bedroom Eco Mode"
        value_template: >-
          {% if is_state_attr('climate.master_bedroom_aircon','preset_mode','eco') %}
            On
          {% elif is_state_attr('climate.master_bedroom_aircon','preset_mode','none') %}
            Off
          {% else %}
            Off
          {% endif %}
        icon_template: >-
          {% if is_state_attr('climate.master_bedroom_aircon','preset_mode','eco') %}
            mdi:home-lightning-bolt
          {% elif is_state_attr('climate.master_bedroom_aircon','preset_mode','none') %}
            mdi:home-lightning-bolt-outline
          {% else %}
            mdi:home-lightning-bolt-outline
          {% endif %}
      master_bedroom_aircon_fan_mode:
        friendly_name: "Master Bedroom Aircon Fan Mode"
        value_template: >
          {{ state_attr('climate.master_bedroom_aircon','fan_mode') }}
        icon_template: >
          {% if is_state_attr('climate.master_bedroom_aircon','fan_mode','Auto') %}
            mdi:fan-auto
          {% elif is_state_attr('climate.master_bedroom_aircon','fan_mode','Low') %}
            mdi:fan-speed-1
          {% elif is_state_attr('climate.master_bedroom_aircon','fan_mode','Medium') %}
            mdi:fan-speed-2
          {% elif is_state_attr('climate.master_bedroom_aircon','fan_mode','High') %}
            mdi:fan-speed-3
          {% else %}
            mdi:fan-off
          {% endif %}

input_boolean:
  master_bedroom_nighttime_protocol:
    name: Master Bedroom Nighttime Protocol
    icon: mdi:lightbulb-night
  kallen_bedtime_protocol:
    name: Kallen Bedtime Protocol
    icon: mdi:lightbulb-night
  # Turn on when master bedroom air conditioner is installed, turn off in winter when we take it out, for smarter automations
  master_bedroom_aircon_installed:
    name: Master Bedroom Aircon Installed
    icon: mdi:tools
  # Same thing, but for the nursery air conditioner
  nursery_aircon_installed:
    name: Nursery Aircon Installed
    icon: mdi:tools
  # Used internally for automations to know if cooling time has passed or not
  master_bedroom_cooling_on:
    name: Master Bedroom Cooling On

input_number:
  master_bedroom_daytime_temp:
    name: Master Bedroom Daytime Temp
    min: 65
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_night_temp:
    name: Master Bedroom Night Temp
    min: 65
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_bedtime_temp:
    name: Master Bedroom Bedtime Temp
    min: 65
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
