sensor:
  - platform: template
    sensors:
      master_bedroom_current_temp:
        friendly_name: "Master Bedroom Current Temp"
        unique_id: 40c6b591-09d3-45cd-8cab-9838517cc08a
        value_template: "{{ state_attr('climate.master_bedroom_aircon','current_temperature') | float }}"
        availability_template: "{{ states('climate.master_bedroom_aircon') not in ['unavailable','unknown'] }}"
      master_bedroom_outdoor_temp:
        friendly_name: "Master Bedroom Outdoor Temp"
        unique_id: 1a79ac59-0faf-4de5-b546-5d6d5e151dd6
        value_template: "{{ state_attr('climate.master_bedroom_aircon','outdoor_temperature') | float }}"
        availability_template: "{{ states('climate.master_bedroom_aircon') not in ['unavailable','unknown'] }}"
      master_bedroom_target_temp:
        friendly_name: "Master Bedroom Target Temp"
        unique_id: 2ce31844-b115-42b8-8213-feccf24e236c
        value_template: "{{ state_attr('climate.master_bedroom_aircon','temperature') | float }}"
        availability_template: "{{ states('climate.master_bedroom_aircon') not in ['unavailable','unknown'] }}"
      master_bedroom_aircon_eco_mode:
        friendly_name: "Master Bedroom Eco Mode"
        unique_id: edf36e23-adcf-4506-80eb-a14f4ea2fce0
        value_template: "{{ is_state_attr('climate.master_bedroom_aircon','preset_mode','eco') }}"
        icon_template: >-
          {% if is_state_attr('climate.master_bedroom_aircon','preset_mode','eco') %}
            mdi:home-lightning-bolt
          {% else %}
            mdi:home-lightning-bolt-outline
          {% endif %}
        availability_template: "{{ states('climate.master_bedroom_aircon') not in ['unavailable','unknown'] }}"
      master_bedroom_aircon_fan_mode:
        friendly_name: "Master Bedroom Aircon Fan Mode"
        unique_id: c0e4f9ba-0c6c-4673-9a75-13f253f2f2e8
        value_template: "{{ state_attr('climate.master_bedroom_aircon','fan_mode') }}"
        icon_template: >
          {% if is_state_attr('climate.master_bedroom_aircon','fan_mode','Auto') %}
            mdi:fan-auto
          {% elif is_state_attr('climate.master_bedroom_aircon','fan_mode','Low') %}
            mdi:fan-speed-1
          {% elif is_state_attr('climate.master_bedroom_aircon','fan_mode','Medium') %}
            mdi:fan-speed-2
          {% elif is_state_attr('climate.master_bedroom_aircon','fan_mode','High') %}
            mdi:fan-speed-3
          {% else %}
            mdi:fan-off
          {% endif %}
        availability_template: "{{ states('climate.master_bedroom_aircon') not in ['unavailable','unknown'] }}"

template:
  - binary_sensor:
    - name: Emma Aircon - Compressor
      unique_id: 21bcbb62-823c-43ff-8c2c-26e940324ee6
      state: "{{ is_state('fan.emma_air_conditioner','on') and states('sensor.emma_air_conditioner_power') | int > 150 }}"
      device_class: running
    - name: Emma Aircon - Fan
      unique_id: 9e3054cf-8f7e-4fef-9da4-5b2f2bc99c9d
      state: "{{ is_state('fan.emma_air_conditioner','on') and states('sensor.emma_air_conditioner_power') | int > 20 }}"
      device_class: running
    - name: Master Bedroom Aircon - Compressor
      unique_id: 87051957-1dbc-4d65-b138-e8469728f58f
      state: "{{ states('climate.master_bedroom_aircon') not in ['off','unknown','unavailable'] and states('sensor.master_bedroom_aircon_power') | int > 150 }}"
      device_class: running
    - name: Master Bedroom Aircon - Fan
      unique_id: ae893dd6-129c-4886-a966-a89b958d9f08
      state: "{{ states('climate.master_bedroom_aircon') not in ['off','unknown','unavailable'] and states('sensor.master_bedroom_aircon_power') | int > 20 }}"
      device_class: running
    - name: Kallen Fan - Separate Schedule
      unique_id: 3f243861-6a1f-412f-b9e3-933b54793b08
      state: "{{ states('input_datetime.kallen_fan') != states('input_datetime.kallen_bedtime') }}"

input_boolean:
  master_bedroom_nighttime_protocol:
    name: Master Bedroom Nighttime Protocol
    icon: mdi:lightbulb-night
  kallen_bedtime_protocol:
    name: Kallen Bedtime Protocol
    icon: mdi:lightbulb-night

  # Turn on when master bedroom air conditioner is installed, turn off in winter when we take it out, for smarter automations
  master_bedroom_aircon_installed:
    name: Master Bedroom Aircon Installed
    icon: mdi:tools

  # Same thing, but for Emma's bedroom air conditioner
  emma_bedroom_aircon_installed:
    name: Emma Bedroom Aircon Installed
    icon: mdi:tools

  # Used internally for automations to know if cooling time has passed or not
  master_bedroom_cooling_on:
    name: Master Bedroom Cooling On
    icon: mdi:snowflake

  # Activated if the day will be excessively hot. For use with automations for daytime climate control.
  hot_day:
    name: Hot Day
    icon: mdi:heat-wave

  # Activated if the day will be excessively cold. For use with automations for daytime climate control.
  cold_day:
    name: Cold Day
    icon: mdi:snowflake

input_select:
  scheduled_climate_mode_master_bedroom_aircon:
    name: Scheduled Climate Mode - Master Bedroom Aircon
    options:
      - AC
      - Fan
      - N/A
    icon: mdi:home-thermometer
  scheduled_climate_mode_master_bedroom_fan:
    name: Scheduled Climate Mode - Master Bedroom Fan
    options:
      - Fan
      - N/A
    icon: mdi:home-thermometer
  scheduled_climate_mode_emma_aircon:
    name: Scheduled Climate Mode - Emma Aircon
    options:
      - AC
      - White Noise
      - N/A
    icon: mdi:home-thermometer
  naptime_climate_mode_emma_aircon:
    name: Naptime Climate Mode - Emma Aircon
    options:
      - AC
      - White Noise
      - N/A
    icon: mdi:home-thermometer
  scheduled_climate_mode_kallen_fan:
    name: Scheduled Climate Mode - Kallen Fan
    options:
      - Fan
      - White Noise
      - N/A
    icon: mdi:home-thermometer

input_number:
  master_bedroom_daytime_temp:
    name: Master Bedroom Daytime Temp
    min: 65
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_night_temp:
    name: Master Bedroom Night Temp
    min: 65
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_bedtime_temp:
    name: Master Bedroom Bedtime Temp
    min: 65
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_aircon_run_threshold:
    name: Master Bedroom Aircon Run Threshold
    min: 40
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_aircon_mode_threshold:
    name: Master Bedroom Aircon Mode Threshold
    min: 40
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_fan_threshold:
    name: Master Bedroom Fan Threshold
    min: 30
    max: 70
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  master_bedroom_daytime_threshold:
    name: Master Bedroom Daytime Threshold
    min: 60
    max: 90
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  emma_aircon_threshold:
    name: Emma Aircon Threshold
    min: 40
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  emma_naptime_aircon_threshold:
    name: Emma Naptime Aircon Threshold
    min: 40
    max: 80
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  kallen_fan_threshold:
    name: Kallen Fan Threshold
    min: 40
    max: 70
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  hot_day_threshold:
    name: Hot Day Threshold
    min: 70
    max: 100
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  heat_index_threshold:
    name: Heat Index Threshold
    min: 70
    max: 100
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  cold_day_threshold:
    name: Cold Day Threshold
    min: 0
    max: 40
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  overnight_low_threshold:
    name: Overnight Low Threshold
    min: -20
    max: 20
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer
  wind_chill_threshold:
    name: Wind Chill Threshold
    min: 0
    max: 40
    step: 1
    unit_of_measurement: °F
    icon: mdi:thermometer