sensor:
  - platform: statistics
    unique_id: fcf4e80e-8459-4e23-a94f-5f127b628c20
    name: Local Maximum Gas Price Filtered
    entity_id: sensor.local_maximum_gas_price
    state_characteristic: mean
    max_age:
      hours: 24
  - platform: statistics
    unique_id: 6a8c9dd1-980c-45b2-bbc1-c5f1777d434a
    name: Local Minimum Gas Price Filtered
    entity_id: sensor.local_minimum_gas_price
    state_characteristic: mean
    max_age:
      hours: 24
