# This file is for entities/automations that are specific to Kallen

input_boolean:
  kallen_sleeping:
    name: Kallen Sleeping
    icon: mdi:sleep
  kallen_computer_updates:
    name: Kallen Computer Updates
    icon: mdi:update
  kallen_overnight:
    name: Kallen Overnight
    icon: mdi:weather-night
  kallen_awake:
    name: Kallen Awake
    icon: mdi:eye-check
  kallen_late_bedtime:
    name: Kallen Late Bedtime
    icon: mdi:weather-night
  kallen_morning_meds_reminder:
    name: Kallen Morning Meds Reminder
    icon: mdi:medication
  kallen_morning_meds_taken:
    name: Kallen Morning Meds Taken
    icon: mdi:medication
  kallen_night_meds_reminder:
    name: Kallen Night Meds Reminder
    icon: mdi:medication
  kallen_night_meds_taken:
    name: Kallen Night Meds Taken
    icon: mdi:medication
  kallen_alarm_clock:
    name: Kallen Alarm Clock
    icon: mdi:alarm
  kallen_has_phone:
    name: Kallen Has Phone
    icon: mdi:cellphone

input_datetime:
  kallen_bedtime:
    name: Kallen Bedtime
    has_date: false
    has_time: true
    icon: mdi:weather-night
  kallen_wakeup_time:
    name: Kallen Wake-up Time
    has_date: false
    has_time: true
    icon: mdi:bell-alert
  kallen_asleep_at:
    name: Kallen Asleep At
    has_date: false
    has_time: true
    icon: mdi:weather-night
  kallen_awake_at:
    name: Kallen Awake At
    has_date: false
    has_time: true
    icon: mdi:weather-sunset-up
  kallen_fan:
    name: Kallen Fan
    has_date: false
    has_time: true
    icon: mdi:fan-auto
  kallen_morning_meds_taken:
    name: Kallen Morning Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  kallen_night_meds_taken:
    name: Kallen Night Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  kallen_morning_meds_notify:
    name: Kallen Morning Meds Notify
    has_date: true
    has_time: true
    icon: mdi:medication
  kallen_night_meds_notify:
    name: Kallen Night Meds Notify
    has_date: true
    has_time: true
    icon: mdi:medication
  kallen_alarm_clock:
    name: Kallen Alarm Clock
    has_date: false
    has_time: true
    icon: mdi:alarm

sensor:
- platform: rest
  name: Kallen Tasks
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    project_id: 2285969005
  headers:
    Authorization: !secret todoist_api_token
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - project
    - items
  scan_interval: 30

automation:
  - id: 94b57d79-efe0-4f34-b5e3-baeaa5eea9f4
    alias: Kallen Asleep
    trigger:
      - platform: time
        at: input_datetime.kallen_bedtime
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kallen_awake