# Hue bulbs seem to be auto discovered just fine. This file will be for anything that is not auto discovered.

sensor:
  - platform: powercalc
    entity_id: light.basement_led_strip_1
    manufacturer: lifx
    model: LIFX Z/length_4
    create_energy_sensor: true
    create_utility_meters: true
    power_sensor_naming: "{} Power Sensor"
    energy_sensor_naming: "{} Energy Sensor"
    mode: lut
  - platform: powercalc
    create_group: Living Room Lights
    include:
      group: light.living_room_lights
  - platform: powercalc
    create_group: Upstairs Bathroom Lights
    include:
      group: light.upstairs_bathroom_lights
  - platform: powercalc
    create_group: Downstairs Bathroom Lights
    include:
      group: light.downstairs_bathroom_lights
  - platform: powercalc
    create_group: Master Bedroom Lights
    include:
      group: light.master_bedroom_lights
  - platform: powercalc
    create_group: Kallen Bedroom Lights
    include:
      group: light.kallen_bedroom_lights
  - platform: powercalc
    create_group: Basement Studio Lights
    include:
      group: light.basement_studio_lights