# Hue bulbs seem to be auto discovered just fine. This file will be for anything that is not auto discovered.

sensor:
  - platform: powercalc
    entity_id: light.basement_led_strip_1
    manufacturer: lifx
    model: LIFX Z/length_4
    create_energy_sensor: true
    create_utility_meters: true
    power_sensor_naming: "{} Power Sensor"
    energy_sensor_naming: "{} Energy Sensor"
    mode: lut
  - platform: powercalc
    entity_id: switch.basement_server
    power_sensor_id: sensor.basement_server_power
  - platform: powercalc
    entity_id: switch.tony_desktop
    power_sensor_id: sensor.tony_desktop_power
  - platform: powercalc
    entity_id: switch.kallen_desktop
    power_sensor_id: sensor.kallen_desktop_power
  - platform: powercalc
    entity_id: fan.emma_air_conditioner
    power_sensor_id: sensor.emma_air_conditioner_power
  - platform: powercalc
    entity_id: fan.kallen_bedroom_fan
    power_sensor_id: sensor.kallen_bedroom_fan_power
  - platform: powercalc
    entity_id: fan.master_bedroom_fan
    power_sensor_id: sensor.master_bedroom_fan_power
  - platform: powercalc
    entity_id: fan.basement_fan
    power_sensor_id: sensor.basement_fan_power
  - platform: powercalc
    create_group: Living Room Lights
    include:
      group: light.living_room_lights
  - platform: powercalc
    create_group: Upstairs Bathroom Lights
    include:
      group: light.upstairs_bathroom_lights
  - platform: powercalc
    create_group: Downstairs Bathroom Lights
    include:
      group: light.downstairs_bathroom_lights
  - platform: powercalc
    create_group: Master Bedroom Lights
    include:
      group: light.master_bedroom_lights
  - platform: powercalc
    create_group: Kallen Bedroom Lights
    include:
      group: light.kallen_bedroom_lights
  - platform: powercalc
    create_group: Basement Studio Lights
    include:
      group: light.basement_studio_lights
  - platform: powercalc
    create_group: First Floor Lights
    include:
      group: light.first_floor_light_bulbs
  - platform: powercalc
    create_group: Second Floor Lights
    include:
      group: light.second_floor_light_bulbs
  - platform: powercalc
    create_group: Master Bedroom All Lights
    include:
      area: master_bedroom