automation:
  - id: c772b54d-6448-4d74-a0c2-32998f49b17c
    alias: Kallen Scheduling - Morning
    trigger:
      platform: time
      at: '06:05:00'
    action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.kallen_wakeup_time
      data_template:
        time: >
          {% if is_state('input_boolean.school_today', 'on') %}
            07:30
          {% else %}
            08:00
          {% endif %}
    - service: input_datetime.set_datetime
      entity_id: input_datetime.kallen_morning_briefing
      data_template:
        time: >
          {% if is_state('input_boolean.school_today', 'on') %}
            07:40
          {% else %}
            10:00
          {% endif %}

  - id: 0335656c-b5cf-4983-bbac-a2d71ca2b74e
    alias: Kallen Scheduling - Evening
    trigger:
      platform: time
      at: '16:00:00'
    action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.kallen_bedtime
      data_template:
        time: >
          {% if is_state('sensor.school_tomorrow', 'on') %}
            21:00
          {% else %}
            22:00
          {% endif %}
    - service: input_datetime.set_datetime
      entity_id: input_datetime.kallen_nightly_briefing
      data_template:
        time: >
          {% if is_state('sensor.school_tomorrow', 'on') %}
            20:40
          {% else %}
            21:40
          {% endif %}

  - id: 1c9f7e4b-2d5a-4b95-bd80-d9aa2244a6db
    alias: House Scheduling - Morning
    trigger:
      platform: time
      at: '06:10:00'
    action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.audible_notification_on
      data_template:
        time: >
          {% if is_state('input_boolean.school_today','on') %}
            07:30
          {% else %}
            09:00
          {% endif %}

  - id: 55293e9a-ec3b-46bb-af47-94e95f3c9951
    alias: House Scheduling - Evening
    trigger:
      platform: time
      at: '16:05:00'
    action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.audible_notification_off
      data_template:
        time: >
          {% if is_state('sensor.school_tomorrow','on') %}
            22:00
          {% else %}
            23:00
          {% endif %}

  - id: 89470712-f94d-4c01-8215-ed15b3bc799a
    alias: Master Bedroom Scheduling
    trigger:
      - platform: time
        at: '06:07:00'
        id: mrbedroom-morning
      - platform: time
        at: '20:45:00'
        id: mrbedroom-evening
    action:
      - if:
        - condition: trigger
          id: mrbedroom-morning
        then:
          - service: input_datetime.set_datetime
            entity_id: input_datetime.master_bedroom_wakeup
            data_template:
              time: >
                {% if is_state('input_boolean.school_today','on') %}
                  13:45
                {% else %}
                  13:00
                {% endif %}
      - if:
        - condition: trigger
          id: mrbedroom-evening
        then:
          - service: input_datetime.set_datetime
            entity_id: input_datetime.master_bedroom_cooling
            data_template:
              time: >
                {% set low = state_attr('sensor.current_forecast','overnight_low') | float %}
                {% if low > 55 and low < 60 %}
                  22:00
                {% elif low > 60 %}
                  21:00
                {% else %}
                  00:00
                {% endif %}