intent_script:
  SetTimer:
    action:
      service: timer.start
      target:
        entity_id: "{{ room }}"
      data:
        duration: >
          {% if unit == 'hours' %}
            {{ (time * 60) * 60 }}
          {% elif unit == 'minutes' %}
            {{ time * 60}}
          {% elif unit == 'seconds' %}
            {{ time }}
          {% endif %}
    speech:
      text: "Okay"
  CancelTimer:
    action:
      service: timer.cancel
      target:
        entity_id: "{{ room }}"
    speech:
      text: "Okay"
  PauseTimer:
    action:
      service: timer.pause
      target:
        entity_id: "{{ room }}"
    speech:
      text: "Okay"
  ResumeTimer:
    action:
      service: timer.start
      target:
        entity_id: "{{ room }}"
    speech:
      text: "Okay"

automation:
  - id: 849b72f0-89e9-421b-9e75-01a6d977488d
    alias: Timer Handling
    description: This automation will handle when house timers (usually set by voice) are finished
    mode: queued
    max: 10
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_timer
      id: kitchen-finished
    action:
    - choose:
      - conditions: "{{ trigger.id == 'kitchen-finished' }}"
        sequence:
        - service: script.speech_engine
          data:
            type: normal
            who: common
            message: "The timer for the kitchen is finished"