# This file is for entities/automations that are specific to Tony

input_boolean:
  tony_streaming_today:
    name: Tony Streaming Today
    icon: mdi:twitch
  tony_morning_meds_taken:
    name: Tony Morning Meds Taken
    icon: mdi:medication
  tony_afternoon_meds_taken:
    name: Tony Afternoon Meds Taken
    icon: mdi:medication
  tony_night_meds_taken:
    name: Tony Night Meds Taken
    icon: mdi:medication
  tony_ibuprofen_active:
    name: Tony Ibuprofen Active
    icon: mdi:medication
  tony_ibuprofen_taken:
    name: Tony Ibuprofen Taken
    icon: mdi:medication
  tony_tylenol_active:
    name: Tony Tylenol Active
    icon: mdi:medication
  tony_tylenol_taken:
    name: Tony Tylenol Taken
    icon: mdi:medication
  tony_custom_meds_tracker_p1:
    name: Tony Custom Meds Tracker P1
    icon: mdi:medication
  tony_custom_meds_taken_p1:
    name: Tony Custom Meds Taken P1
    icon: mdi:medication
  tony_awake:
    name: Tony Awake
    icon: mdi:eye-check

input_datetime:
  tony_streaming_start_time:
    name: Tony Streaming Start Time
    has_date: false
    has_time: true
    icon: mdi:twitch
  tony_morning_meds_taken:
    name: Tony Morning Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_afternoon_meds_taken:
    name: Tony Afternoon Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_night_meds_taken:
    name: Tony Night Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_morning_meds_notify:
    name: Tony Morning Meds Notify
    has_date: false
    has_time: true
    icon: mdi:medication
  tony_afternoon_meds_notify:
    name: Tony Afternoon Meds Notify
    has_date: false
    has_time: true
    icon: mdi:medication
  tony_night_meds_notify:
    name: Tony Night Meds Notify
    has_date: false
    has_time: true
    icon: mdi:medication
  tony_custom_meds_taken_p1:
    name: Tony Custom Meds Taken P1
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_custom_meds_notify_p1:
    name: Tony Custom Meds Notify P1
    has_date: false
    has_time: true
    icon: mdi:medication
  tony_ibuprofen_taken:
    name: Tony Ibuprofen Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_ibuprofen_notify:
    name: Tony Ibuprofen Notify
    has_date: false
    has_time: true
    icon: mdi:medication
  tony_tylenol_taken:
    name: Tony Tylenol Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_tylenol_notify:
    name: Tony Tylenol Notify
    has_date: false
    has_time: true
    icon: mdi:medication

input_number:
  tony_afternoon_meds_interval:
    name: Tony Afternoon Meds Interval
    min: 0
    max: 12
    step: 1
    unit_of_measurement: hours
    icon: mdi:medication
  tony_custom_meds_interval_p1:
    name: Tony Custom Meds Interval P1
    min: 0
    max: 24
    step: 1
    icon: mdi:medication

input_text:
  tony_custom_med_name_p1:
    name: Tony Custom Med Name P1
    icon: mdi:medication

input_select:
  tony_custom_meds_type_p1:
    name: Tony Custom Meds Type P1
    options:
      - Wakeup
      - Bedtime
      - Other Time
      - Interval
    icon: mdi:medication

sensor:
- platform: rest
  name: Home Tech
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    project_id: 2285967948
  headers:
    Authorization: !secret todoist_api_token
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - project
    - items
  scan_interval: 30