# This file is for entities/automations that are specific to Tony

input_boolean:
  tony_streaming_today:
    name: Tony Streaming Today
    icon: mdi:twitch
  tony_morning_meds_taken:
    name: Tony Morning Meds Taken
    icon: mdi:medication
  tony_night_meds_taken:
    name: Tony Night Meds Taken
    icon: mdi:medication

input_datetime:
  tony_streaming_start_time:
    name: Tony Streaming Start Time
    has_date: false
    has_time: true
    icon: mdi:twitch
  tony_morning_meds_taken:
    name: Tony Morning Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_night_meds_taken:
    name: Tony Night Meds Taken
    has_date: true
    has_time: true
    icon: mdi:medication
  tony_morning_meds_notify:
    name: Tony Morning Meds Notify
    has_date: false
    has_time: true
    icon: mdi:medication
  tony_night_meds_notify:
    name: Tony Night Meds Notify
    has_date: false
    has_time: true
    icon: mdi:medication

sensor:
- platform: rest
  name: Home Tech
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    project_id: 2285967948
  headers:
    Authorization: !secret todoist_api_token
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - project
    - items
  scan_interval: 30