# This file is for anything related to my Twitch streaming and considerations for my studio

input_boolean:
  stream_online:
    name: Stream Online
    icon: mdi:twitch

automation:
  - id: 8b42bbb1-9ec9-4238-a8b5-45d3dfce4ee0
    alias: Stream Online TTS Pause
    description: This will attempt to block non-essential TTS notifications to the studio while stream is live
    trigger:
      - platform: state
        entity_id: input_boolean.stream_online
        from: 'off'
        to: 'on'
        id: stream-live
      - platform: state
        entity_id: input_boolean.stream_online
        from: 'on'
        to: 'off'
        id: stream-offline
    condition:
      - condition: state
        entity_id: binary_sensor.people_present
        state: 'on'
    action:
      - if:
        - condition: trigger
          id: stream-live
        then:
          - service: switch.turn_on
            target:
              entity_id: switch.basement_echo_dot_do_not_disturb_switch
      - if:
        - condition: trigger
          id: stream-offline
        then:
          - service: switch.turn_off
            target:
              entity_id: switch.basement_echo_dot_do_not_disturb_switch
